### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jurra** [CarlosAndresd/f_abm#19]
## Feature Suggestion: Enable your cli program to ingest or process a configuration file that describes a simulation
Have you thought about describing your simulation config in a file, and even store several of them as metadata with even dates, and perhaps version of your package. Then you could pass them as a job configuration, that could be run in parallel.

Is good that the cli ask for each parameter, but it would be also good to simply pass the simulation file as an input. This way your simulation becomes also reusable, documented, and they become source as well.

### How could it be implemented:
First things that comes to my mind is a simulation file that looks like this:
```yaml
# Comment on the simulation
simulation:
    param_1: 10 
    param_2: 90 # Here I explain why I set this parameter

```
More things could develop with this idea, but this is a first suggestion ;)
You could include dates, title, etc....description.....
